# Generated by Django 4.2.2 on 2024-09-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_note_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('#808080', 'Grey'), ('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#FFFF00', 'Yellow'), ('#FFA500', 'Orange'), ('#800080', 'Purple'), ('#000000', 'Black')], default='#808080', max_length=8),
        ),
    ]
